const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');

test('web app exposes Taobao publish assistant page and bridge methods', async () => {
  const index = await fs.readFile(path.join(__dirname, '../../web/index.html'), 'utf8');
  const bridge = await fs.readFile(path.join(__dirname, '../../web/src/api-bridge.js'), 'utf8');
  const renderer = await fs.readFile(path.join(__dirname, '../../web/src/renderer.js'), 'utf8');
  const server = await fs.readFile(path.join(__dirname, '../src/server.js'), 'utf8');

  assert.match(index, /page-taobao-publish/);
  assert.match(index, /taobaoPublishTaskList/);
  assert.match(index, /taobaoCategoryEditor/);
  assert.match(bridge, /getTaobaoPublishSettings/);
  assert.match(bridge, /saveTaobaoPublishSettings/);
  assert.match(bridge, /queueTaobaoPublishTask/);
  assert.match(renderer, /renderTaobaoPublishPage/);
  assert.match(renderer, /saveActiveTaobaoCategoryTemplate/);
  assert.match(renderer, /queueActiveTaobaoPublishTask/);
  assert.match(renderer, /renderTaobaoPublishDiagnostics/);
  assert.match(renderer, /copyTaobaoPublishDiagnostics/);
  assert.match(renderer, /notifyTaobaoExtensionPoll/);
  assert.match(renderer, /CAISHEN_TAOBAO_WEB_TRIGGER/);
  assert.match(renderer, /TAOBAO_SELECTOR_FIELDS/);
  assert.match(renderer, /collectTaobaoSelectors/);
  assert.match(renderer, /categorySearch/);
  assert.match(renderer, /categorySearchButton/);
  assert.match(renderer, /categoryResult/);
  assert.match(renderer, /customFields/);
  assert.match(renderer, /parseJsonArrayField/);
  assert.match(renderer, /mainImages/);
  assert.match(renderer, /saveDraft/);
  assert.match(renderer, /visibleFields/);
  assert.match(renderer, /visibleSelects/);
  assert.match(renderer, /JSON\.stringify\(buttons/);
  assert.match(renderer, /validationError/);
  assert.match(server, /runTaobaoPublishWithToken/);
  assert.match(server, /\/images\/:group\/:index/);
  assert.match(await fs.readFile(path.join(__dirname, '../src/runtime.js'), 'utf8'), /detail: saved\.detail \|\| \{\}/);
  assert.ok(server.indexOf("app.post('/api/taobao/publish/claim'") < server.indexOf("app.use('/api'"));
});
