const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const background = fs.readFileSync(path.join(root, 'src/background.js'), 'utf8');
const content = fs.readFileSync(path.join(root, 'src/content.js'), 'utf8');
const popup = fs.readFileSync(path.join(root, 'src/popup.html'), 'utf8');

assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.background.service_worker, 'src/background.js');
assert.ok(manifest.host_permissions.includes('https://item.upload.taobao.com/*'));
assert.match(background, /\/api\/taobao\/publish\/claim/);
assert.match(background, /CAISHEN_TAOBAO_FETCH_IMAGE/);
assert.match(background, /\/images\/\$\{group\}\/\$\{index\}/);
assert.match(background, /CAISHEN_TAOBAO_STATUS/);
assert.match(background, /schedulePoll/);
assert.match(background, /setTimeout/);
assert.match(background, /Math\.max\(30000, options\.pollSeconds \* 1000\)/);
assert.match(background, /chrome\.tabs\.onRemoved\.addListener/);
assert.match(background, /clearActiveTask/);
assert.match(content, /input\[type="file"\]/);
assert.match(content, /dataUrlToFile/);
assert.match(content, /selectors\(task\)/);
assert.match(content, /selectOptionByText/);
assert.match(content, /isSelectLike/);
assert.match(content, /setSelectValue/);
assert.match(content, /fallbackAllImages/);
assert.match(content, /uploadBusyElements/);
assert.match(content, /waitForUploadSettled/);
assert.match(content, /upload-settled/);
assert.match(content, /collectDiagnostics/);
assert.match(content, /collectVisibleFields/);
assert.match(content, /collectVisibleSelects/);
assert.match(content, /saveDraft/);
assert.match(content, /waitForDraftSaved/);
assert.match(content, /findValidationError/);
assert.doesNotMatch(content, /successKeywords[\s\S]*'\\u8349\\u7a3f'/);
assert.match(popup, /token/);

console.log('taobao extension smoke test passed');
