const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const background = fs.readFileSync(path.join(root, 'src/background.js'), 'utf8');
const content = fs.readFileSync(path.join(root, 'src/content.js'), 'utf8');
const shared = fs.readFileSync(path.join(root, 'src/shared.js'), 'utf8');
const webBridge = fs.readFileSync(path.join(root, 'src/web-bridge.js'), 'utf8');
const popup = fs.readFileSync(path.join(root, 'src/popup.html'), 'utf8');
const popupJs = fs.readFileSync(path.join(root, 'src/popup.js'), 'utf8');

assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.background.service_worker, 'src/background.js');
assert.ok(manifest.host_permissions.includes('https://item.upload.taobao.com/*'));
assert.ok(manifest.host_permissions.includes('http://127.0.0.1/*'));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/web-bridge.js')));
assert.match(shared, /http:\/\/127\.0\.0\.1:3008/);
assert.doesNotMatch(shared, /127\.0\.0\.1:8790/);
assert.match(background, /\/api\/taobao\/publish\/claim/);
assert.match(background, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(background, /CAISHEN_TAOBAO_FETCH_IMAGE/);
assert.match(background, /\/images\/\$\{group\}\/\$\{index\}/);
assert.match(background, /CAISHEN_TAOBAO_STATUS/);
assert.match(background, /schedulePoll/);
assert.match(background, /setTimeout/);
assert.match(background, /Math\.max\(30000, options\.pollSeconds \* 1000\)/);
assert.match(background, /chrome\.tabs\.onRemoved\.addListener/);
assert.match(background, /chrome\.tabs\.onUpdated\.addListener/);
assert.match(background, /clearActiveTask/);
assert.match(background, /trySendTaskToActiveTab/);
assert.match(background, /findExistingPublishTab/);
assert.match(background, /chrome\.tabs\.query\(\{ url: 'https:\/\/item\.upload\.taobao\.com\/\*' \}\)/);
assert.match(background, /chrome\.tabs\.update\(existingTab\.id, \{ active: true \}\)/);
assert.match(background, /injectContentScript/);
assert.match(background, /chrome\.scripting\.executeScript/);
assert.match(background, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(background, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /input\[type="file"\]/);
assert.match(content, /标题/);
assert.match(content, /价格/);
assert.match(content, /上传图片/);
assert.match(content, /保存草稿/);
assert.match(content, /dataUrlToFile/);
assert.match(content, /selectors\(task\)/);
assert.match(content, /selectOptionByText/);
assert.match(content, /isSelectLike/);
assert.match(content, /setSelectValue/);
assert.match(content, /fallbackAllImages/);
assert.match(content, /fileInputFromSelector/);
assert.match(content, /queryFileInput/);
assert.match(content, /uploadBusyElements/);
assert.match(content, /waitForUploadSettled/);
assert.match(content, /upload-settled/);
assert.match(content, /collectDiagnostics/);
assert.match(content, /collectVisibleFields/);
assert.match(content, /collectVisibleSelects/);
assert.match(content, /fillCustomFields/);
assert.match(content, /customFields/);
assert.match(content, /saveDraft/);
assert.match(content, /waitForDraftSaved/);
assert.match(content, /STATUS\.saved/);
assert.match(content, /savedAt/);
assert.match(content, /findValidationError/);
assert.match(content, /isCategoryEntryPage/);
assert.match(content, /selectTaobaoCategory/);
assert.match(content, /preparePublishForm/);
assert.match(content, /scoreCategoryCandidate/);
assert.match(content, /categoryCandidateText/);
assert.match(content, /genericCategoryLabels/);
assert.match(content, /cssSelectorForDiagnostics/);
assert.match(content, /selectorForElement/);
assert.match(content, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /collectDiagnostics\(error\.step \|\| 'unknown'\)/);
assert.match(content, /KeyboardEvent/);
assert.doesNotMatch(content, /if \(await preparePublishForm\(task\)\) return/);
assert.doesNotMatch(content, /successKeywords[\s\S]*'\\u8349\\u7a3f'/);
assert.match(webBridge, /CAISHEN_TAOBAO_WEB_TRIGGER/);
assert.match(webBridge, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(webBridge, /CAISHEN_TAOBAO_POPUP_SAVE/);
assert.match(webBridge, /baseUrl/);
assert.match(webBridge, /token/);
assert.match(popup, /diagnosticsButton/);
assert.match(popup, /copyDiagnosticsButton/);
assert.match(popup, /diagnosticsOutput/);
assert.match(popupJs, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(popupJs, /navigator\.clipboard\.writeText/);
assert.match(popup, /token/);

console.log('taobao extension smoke test passed');
