const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const background = fs.readFileSync(path.join(root, 'src/background.js'), 'utf8');
const content = fs.readFileSync(path.join(root, 'src/content.js'), 'utf8');
const shared = fs.readFileSync(path.join(root, 'src/shared.js'), 'utf8');
const webBridge = fs.readFileSync(path.join(root, 'src/web-bridge.js'), 'utf8');
const popup = fs.readFileSync(path.join(root, 'src/popup.html'), 'utf8');
const popupJs = fs.readFileSync(path.join(root, 'src/popup.js'), 'utf8');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

assert.equal(manifest.manifest_version, 3);
assert.equal(manifest.background.service_worker, 'src/background.js');
assert.ok(manifest.host_permissions.includes('https://item.upload.taobao.com/*'));
assert.ok(manifest.host_permissions.includes('http://66.42.101.154:8788/*'));
assert.ok(!manifest.host_permissions.includes('http://127.0.0.1/*'));
assert.ok(!manifest.host_permissions.includes('http://localhost/*'));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/web-bridge.js')));
assert.ok(manifest.content_scripts.some(item => item.js.includes('src/content.js') && item.all_frames === true));
assert.match(shared, /http:\/\/66\.42\.101\.154:8788/);
assert.match(shared, /refreshToken/);
assert.match(shared, /ensureToken/);
assert.doesNotMatch(shared, /127\.0\.0\.1:8790/);
assert.doesNotMatch(popup, /baseUrl/);
assert.match(popup, /id="token"/);
assert.match(popup, /refreshTokenButton/);
assert.match(background, /\/api\/taobao\/publish\/claim/);
assert.match(background, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(background, /CAISHEN_TAOBAO_FETCH_IMAGE/);
assert.match(background, /\/images\/\$\{group\}\/\$\{index\}/);
assert.match(background, /CAISHEN_TAOBAO_STATUS/);
assert.match(background, /schedulePoll/);
assert.match(background, /clearLastError/);
assert.match(background, /chrome\.storage\.local\.remove\(\['lastError', 'lastErrorAt'\]\)/);
assert.match(background, /setTimeout/);
assert.match(background, /Math\.max\(30000, options\.pollSeconds \* 1000\)/);
assert.match(background, /chrome\.tabs\.onRemoved\.addListener/);
assert.match(background, /chrome\.tabs\.onUpdated\.addListener/);
assert.match(background, /clearActiveTask/);
assert.match(background, /trySendTaskToActiveTab/);
assert.match(background, /activeFrameId/);
assert.match(background, /lastFrameCandidates/);
assert.match(background, /findPublishFrame/);
assert.match(background, /frameCandidates/);
assert.match(background, /frame-selected/);
assert.match(background, /allFrames: true/);
assert.match(background, /frameId: activeFrameId/);
assert.match(background, /findExistingPublishTab/);
assert.match(background, /chrome\.tabs\.query\(\{ url: 'https:\/\/item\.upload\.taobao\.com\/\*' \}\)/);
assert.match(background, /chrome\.tabs\.update\(existingTab\.id, \{ url: publishUrl, active: false \}\)/);
assert.match(background, /chrome\.tabs\.create\(\{ url: publishUrl, active: false \}\)/);
assert.match(background, /injectContentScript/);
assert.match(background, /chrome\.scripting\.executeScript/);
assert.match(background, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(background, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /input\[type="file"\]/);
assert.match(content, /标题/);
assert.match(content, /价格/);
assert.match(content, /上传图片/);
assert.match(content, /保存草稿/);
assert.match(content, /dataUrlToFile/);
assert.match(content, /selectors\(task\)/);
assert.match(content, /selectOptionByText/);
assert.match(content, /isSelectLike/);
assert.match(content, /setSelectValue/);
assert.match(content, /if \(isSelectLike\(selected\)\) return setSelectValue\(selected, value\)/);
assert.match(content, /clickElement/);
assert.match(content, /scrollIntoView/);
assert.match(content, /aria-disabled/);
assert.match(content, /element\.click\?\.\(\)/);
assert.doesNotMatch(content, /for \(const type of \['pointerdown', 'mousedown', 'mouseup', 'click'\]\)/);
assert.match(content, /waitForButton/);
assert.match(content, /fallbackAllImages/);
assert.match(content, /fileInputFromSelector/);
assert.match(content, /queryFileInput/);
assert.match(content, /uploadBusyElements/);
assert.match(content, /waitForUploadSettled/);
assert.match(content, /upload-settled/);
assert.match(content, /collectDiagnostics/);
assert.match(content, /collectVisibleFields/);
assert.match(content, /collectVisibleSelects/);
assert.match(content, /fillCustomFields/);
assert.match(content, /customFields/);
assert.match(content, /saveDraft/);
assert.match(content, /waitForDraftSaved/);
assert.match(content, /confirmSaveDraftIfPrompted/);
assert.match(content, /confirmSaveDraftIfPrompted\(button\)/);
assert.match(content, /element !== excludedButton/);
assert.doesNotMatch(content, /confirmSaveDraftIfPrompted\(\)[\s\S]*?findButton\(\[[\s\S]*?'保存'[\s\S]*?\]\)/);
assert.match(content, /STATUS\.saved/);
assert.match(content, /savedAt/);
assert.match(content, /findValidationError/);
assert.match(content, /isCategoryEntryPage/);
assert.match(content, /function isTaobaoLoginPage/);
assert.ok(content.includes("return /login\\.taobao\\.com/i.test(location.hostname)"));
assert.match(content, /if \(isTaobaoLoginPage\(\)\) throw fail\([^\n]+, 'login'\)/);
assert.doesNotMatch(content, /\/category\\\.htm\/i\.test\(location\.href\)/);
assert.match(content, /selectTaobaoCategory/);
assert.match(content, /preparePublishForm/);
assert.match(content, /scoreCategoryCandidate/);
assert.match(content, /ownKeywordHit/);
assert.match(content, /score \+= 60/);
assert.match(content, /categoryOwnLabelIncludesKeyword/);
assert.match(content, /const directCandidates = candidates\.filter/);
assert.match(content, /directCandidates\[0\]\?\.element/);
assert.match(content, /categoryCandidateText/);
assert.match(content, /genericCategoryLabels/);
assert.match(content, /findCategoryAction/);
assert.match(content, /findCategoryContinuation/);
assert.match(content, /categoryActionLabel/);
assert.match(content, /categoryAttempt/);
assert.match(content, /visibleButtons: buttons,[\s\S]*categoryAttempt/);
assert.match(content, /const continuation = findCategoryContinuation\(selected, selected\)/);
assert.match(content, /const fallbackAction = findCategoryAction\(selected, keyword\)/);
assert.ok(content.indexOf('clickElement(selected)') < content.indexOf('const continuation = findCategoryContinuation(selected, selected)'));
assert.ok(content.indexOf('const continuation = findCategoryContinuation(selected, selected)') < content.indexOf('const fallbackAction = findCategoryAction(selected, keyword)'));
assert.match(content, /if \(await waitForPublishForm\(3500\)\) return/);
assert.match(content, /label\.includes\('\\u4e0b\\u4e00\\u6b65'\)/);
assert.match(content, /cssSelectorForDiagnostics/);
assert.match(content, /selectorForElement/);
assert.match(content, /CAISHEN_TAOBAO_COLLECT_DIAGNOSTICS/);
assert.match(content, /collectDiagnostics\(error\.step \|\| 'unknown'\)/);
assert.match(content, /KeyboardEvent/);
assert.match(content, /runningTaskId/);
assert.match(content, /if \(runningTaskId === message\.task\?\.id\)/);
assert.doesNotMatch(content, /if \(await preparePublishForm\(task\)\) return/);
assert.doesNotMatch(content, /successKeywords[\s\S]*'\\u8349\\u7a3f'/);
assert.match(webBridge, /CAISHEN_TAOBAO_WEB_TRIGGER/);
assert.match(webBridge, /CAISHEN_TAOBAO_WEB_SYNC/);
assert.match(webBridge, /CAISHEN_TAOBAO_TRIGGER_POLL/);
assert.match(webBridge, /CAISHEN_TAOBAO_POPUP_SAVE/);
assert.doesNotMatch(webBridge, /baseUrl/);
assert.match(webBridge, /token/);
assert.match(popup, /diagnosticsButton/);
assert.match(popup, /copyDiagnosticsButton/);
assert.match(popup, /diagnosticsOutput/);
assert.match(popupJs, /CAISHEN_TAOBAO_POPUP_DIAGNOSTICS/);
assert.match(popupJs, /CAISHEN_TAOBAO_POPUP_REFRESH_TOKEN/);
assert.match(popupJs, /if \(options\.token\)/);
assert.match(popupJs, /令牌已由 Web 端自动同步/);
assert.match(popupJs, /navigator\.clipboard\.writeText/);
assert.match(popup, /token/);
assert.match(packageJson.scripts.package, /package-extension\.ps1/);
assert.ok(fs.existsSync(path.join(root, 'scripts/package-extension.ps1')));

console.log('taobao extension smoke test passed');
